version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      timezone: Etc/UTC
    groups:
      github-actions:
        patterns:
          - "*"
    allow:
      - dependency-type: all
    cooldown:
      default-days: 7