name: Manage stale issues

on:
  push:
    paths:
      - .github/workflows/stale-issues.yml
    branches-ignore:
      - dependabot/**
  schedule:
    # Once every day at midnight UTC
    - cron: "0 0 * * *"
  issue_comment:

permissions: {}

defaults:
  run:
    shell: bash -xeuo pipefail {0}

concurrency:
  group: stale-issues
  cancel-in-progress: ${{ github.event_name != 'issue_comment' }}

jobs:
  stale:
    if: >
      github.event_name != 'issue_comment' || (
        contains(github.event.issue.labels.*.name, 'stale')
      )
    runs-on: ubuntu-slim
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Mark/Close Stale Issues and Pull Requests
        uses: actions/stale@1e223db275d687790206a7acac4d1a11bd6fe629
        with:
          repo-token: ${{ secrets.PAT_STALE }}
          days-before-stale: 7
          days-before-close: 3
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not
            had recent activity. It will be closed if no further activity
            occurs.
          stale-pr-message: >
            This pull request has been automatically marked as stale because it
            has not had recent activity. It will be closed if no further
            activity occurs.
          exempt-issue-labels: "keep-open"
          exempt-pr-labels: "keep-open"
          delete-branch: true
